GET http://localhost:8080/calculator
###
GET http://localhost:8080/calculator/plus?num1=5&num2=5
###
GET http://localhost:8080/calculator/minus?num1=5&num2=5
###
GET http://localhost:8080/calculator/multiply?num1=5&num2=5
###
GET http://localhost:8080/calculator/divide?num1=5&num2=5
###
GET http://localhost:8080/calculator/divide?num1=5&num2=0
###
GET http://localhost:8080/calculator/plus?num1=
###
GET http://localhost:8080/calculator/divide?num1=
###
GET http://localhost:8080/calculator/multiply
###
GET http://localhost:8080/calculator/minus?num1=5&num2=к
###
GET http://localhost:8080/calculator/plus?num1=-5&num2=5
###
GET http://localhost:8080/calculator/divide?num1=-5&num2=8